local side = require("sides")
local C = "COOLANT_CELL"
local F = "FUEL_ROD"
local D = "FUEL_ROD_DEPLETED"

return {
  MAX_FIX_RETRIES = 10,

  REACTOR_ADAPTER_TARGET_SIDE = side.top,
  MAX_OPERATING_HEAT_PCT = 0.10,
  MAX_COOLANT_DMG_PCT = 0.90,

  REDSTONE_ALARM_SIDE = side.west,
  REDSTONE_COOLANT_SIDE = side.south,
  REDSTONE_FUEL_SIDE = side.north,

  MIN_LCS_EU_PCT = 0.1,
  MAX_LCS_EU_PCT = 0.9,

  LAYOUT = {
    C, F, F, F, C, F, F, C, F,
    F, F, C, F, F, F, F, C, F,
    C, F, F, F, F, C, F, F, F,
    F, F, F, C, F, F, F, F, C,
    F, C, F, F, F, F, C, F, F,
    F, C, F, F, C, F, F, F, C
  },

  KNOWN_ITEMS = {
    COOLANT_CELL = C,
    FUEL_ROD = F,
    FUEL_ROD_DEPLETED = D,
    ["IC2:reactorCoolantSimple"] = C,
    ["IC2:reactorCoolantTriple"] = C,
    ["IC2:reactorCoolantSix"] = C,
    ["gregtech:gt.60k_NaK_Coolantcell"] = C,
    ["gregtech:gt.180k_NaK_Coolantcell"] = C,
    ["gregtech:gt.360k_NaK_Coolantcell"] = C,
    ["gregtech:gt.60k_Helium_Coolantcell"] = C,
    ["gregtech:gt.180k_Helium_Coolantcell"] = C,
    ["gregtech:gt.360k_Helium_Coolantcell"] = C,
    ["gregtech:gt.180k_Space_Coolantcell"] = C,
    ["gregtech:gt.360k_Space_Coolantcell"] = C,
    ["gregtech:gt.540k_Space_Coolantcell"] = C,
    ["gregtech:gt.1080k_Space_Coolantcell"] = C,

    ["gregtech:gt.rodThorium"] = F,
    ["gregtech:gt.rodThorium2"] = F,
    ["gregtech:gt.rodThorium4"] = F,
    ["gregtech:gt.rodUranium"] = F,
    ["gregtech:gt.rodUranium2"] = F,
    ["gregtech:gt.rodUranium4"] = F,
    ["gregtech:gt.rodHighDensityUranium"] = F,
    ["gregtech:gt.rodHighDensityUranium2"] = F,
    ["gregtech:gt.rodHighDensityUranium4"] = F,
    ["gregtech:gt.rodExcitedUranium"] = F,
    ["gregtech:gt.rodExcitedUranium2"] = F,
    ["gregtech:gt.rodExcitedUranium4"] = F,
    ["gregtech:gt.rodPlutonium"] = F,
    ["gregtech:gt.rodPlutonium2"] = F,
    ["gregtech:gt.rodPlutonium4"] = F,
    ["gregtech:gt.rodHighDensityPlutonium"] = F,
    ["gregtech:gt.rodHighDensityPlutonium2"] = F,
    ["gregtech:gt.rodHighDensityPlutonium4"] = F,
    ["gregtech:gt.rodExcitedPlutonium"] = F,
    ["gregtech:gt.rodExcitedPlutonium2"] = F,
    ["gregtech:gt.rodExcitedPlutonium4"] = F,
    ["gregtech:gt.rodMOX"] = F,
    ["gregtech:gt.rodMOX2"] = F,
    ["gregtech:gt.rodMOX4"] = F,
    ["gregtech:gt.rodNaquadah"] = F,
    ["gregtech:gt.rodNaquadah2"] = F,
    ["gregtech:gt.rodNaquadah4"] = F,
    ["gregtech:gt.rodNaquadah32"] = F,
    ["gregtech:gt.rodNaquadria"] = F,
    ["gregtech:gt.rodNaquadria2"] = F,
    ["gregtech:gt.rodNaquadria4"] = F,
    ["gregtech:gt.rodTiberium"] = F,
    ["gregtech:gt.rodTiberium2"] = F,
    ["gregtech:gt.rodTiberium4"] = F,

    ["gregtech:gt.depletedRodThorium"] = D,
    ["gregtech:gt.depletedRodThorium2"] = D,
    ["gregtech:gt.depletedRodThorium4"] = D,
    ["gregtech:gt.depletedRodUranium"] = D,
    ["gregtech:gt.depletedRodUranium2"] = D,
    ["gregtech:gt.depletedRodUranium4"] = D,
    ["gregtech:gt.depletedRodHighDensityUranium"] = D,
    ["gregtech:gt.depletedRodHighDensityUranium2"] = D,
    ["gregtech:gt.depletedRodHighDensityUranium4"] = D,
    ["gregtech:gt.depletedRodExcitedUranium"] = D,
    ["gregtech:gt.depletedRodExcitedUranium2"] = D,
    ["gregtech:gt.depletedRodExcitedUranium4"] = D,
    ["gregtech:gt.depletedRodPlutonium"] = D,
    ["gregtech:gt.depletedRodPlutonium2"] = D,
    ["gregtech:gt.depletedRodPlutonium4"] = D,
    ["gregtech:gt.depletedRodHighDensityPlutonium"] = D,
    ["gregtech:gt.depletedRodHighDensityPlutonium2"] = D,
    ["gregtech:gt.depletedRodHighDensityPlutonium4"] = D,
    ["gregtech:gt.depletedRodExcitedPlutonium"] = D,
    ["gregtech:gt.depletedRodExcitedPlutonium2"] = D,
    ["gregtech:gt.depletedRodExcitedPlutonium4"] = D,
    ["gregtech:gt.depletedRodMOX"] = D,
    ["gregtech:gt.depletedRodMOX2"] = D,
    ["gregtech:gt.depletedRodMOX4"] = D,
    ["gregtech:gt.depletedRodNaquadah"] = D,
    ["gregtech:gt.depletedRodNaquadah2"] = D,
    ["gregtech:gt.depletedRodNaquadah4"] = D,
    ["gregtech:gt.depletedRodNaquadah32"] = D,
    ["gregtech:gt.depletedRodNaquadria"] = D,
    ["gregtech:gt.depletedRodNaquadria2"] = D,
    ["gregtech:gt.depletedRodNaquadria4"] = D,
    ["gregtech:gt.depletedRodTiberium"] = D,
    ["gregtech:gt.depletedRodTiberium2"] = D,
    ["gregtech:gt.depletedRodTiberium4"] = D,
  }
}
