local side = require("sides")
local COOLANT_CELL = 1
local FUEL_ROD_DEPLETED = 2

return {
  REACTOR_ADAPTER_TARGET_SIDE = side.top,
  MAX_OPERATING_HEAT_PCT = 0.10,
  MAX_COOLANT_DMG_PCT = 0.90,

  REDSTONE_ALARM_SIDE = side.west,
  REDSTONE_COOLANT_SIDE = side.south,
  REDSTONE_FUEL_SIDE = side.north,

  MIN_LCS_EU_PCT = 0.1,
  MAX_LCS_EU_PCT = 0.9,

  KNOWN_ITEMS = {
    COOLANT_CELL = COOLANT_CELL,
    FUEL_ROD_DEPLETED = FUEL_ROD_DEPLETED,
    ["IC2:reactorCoolantSimple"] = COOLANT_CELL,
    ["IC2:reactorCoolantTriple"] = COOLANT_CELL,
    ["IC2:reactorCoolantSix"] = COOLANT_CELL,
    ["gregtech:gt.60k_NaK_Coolantcell"] = COOLANT_CELL,
    ["gregtech:gt.180k_NaK_Coolantcell"] = COOLANT_CELL,
    ["gregtech:gt.360k_NaK_Coolantcell"] = COOLANT_CELL,
    ["gregtech:gt.60k_Helium_Coolantcell"] = COOLANT_CELL,
    ["gregtech:gt.180k_Helium_Coolantcell"] = COOLANT_CELL,
    ["gregtech:gt.360k_Helium_Coolantcell"] = COOLANT_CELL,
    ["gregtech:gt.180k_Space_Coolantcell"] = COOLANT_CELL,
    ["gregtech:gt.360k_Space_Coolantcell"] = COOLANT_CELL,
    ["gregtech:gt.540k_Space_Coolantcell"] = COOLANT_CELL,
    ["gregtech:gt.1080k_Space_Coolantcell"] = COOLANT_CELL,
    ["gregtech:gt.depletedRodThorium"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodThorium2"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodThorium4"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodUranium"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodUranium2"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodUranium4"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodHighDensityUranium"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodHighDensityUranium2"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodHighDensityUranium4"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodExcitedUranium"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodExcitedUranium2"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodExcitedUranium4"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodPlutonium"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodPlutonium2"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodPlutonium4"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodHighDensityPlutonium"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodHighDensityPlutonium2"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodHighDensityPlutonium4"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodExcitedPlutonium"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodExcitedPlutonium2"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodExcitedPlutonium4"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodMOX"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodMOX2"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodMOX4"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodNaquadah"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodNaquadah2"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodNaquadah4"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodNaquadah32"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodNaquadria"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodNaquadria2"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodNaquadria4"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodTiberium"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodTiberium2"] = FUEL_ROD_DEPLETED,
    ["gregtech:gt.depletedRodTiberium4"] = FUEL_ROD_DEPLETED,
  }
}
